### ISSUE TITLE
Suggestion-Move a next/refresh button for mobile friendly?

### ISSUE THREAD

**Issue by dbaron92** [sahara101/Movie-Roulette#15]
Suggestion: It might be dumb suggestion but Im wondering if there is a way to add an option (in settings) to move the refresh/next button to above the description but below a poster and movie title.
I made this suggestion because its easier to click the button in mobile version than scroll down to bottom of the page and click next. Then scrolls up to see image/title.

**Comment by sahara101** [comment]
Hmm, I will think about this. Maybe the watch + next buttons and keep the others at the bottom. 
PS: make sure you use PWA, looks a bit better than browser on mobile :P

**Comment by dbaron92** [comment]
Yeah I agree :) I just looked at PWA, and it looks better but has to scroll down little bit for some films that has a lot of descriptions.

**Comment by sahara101** [comment]
Yes, initially I also had truncated the description on mobile but thought it looked better without it.

**Comment by sahara101** [comment]
Thanks for the support!
I released v3.1.1, you will see a new setting to truncate the descriptions on mobile. This way you'll have shorter scrolling to do with 1 line descriptions.

**Comment by dbaron92** [comment]
Welcome! :)
I just updated it and it looks great! I don't use my Mac often but thanks for letting me know though :)

**Comment by sahara101** [comment]
I’ll mark this as solved. :)
