### ISSUE TITLE
Failed to fetch libraries

### ISSUE THREAD

**Issue by xiongster** [sahara101/Movie-Roulette#16]
PLex URL and tocked fetched but after these its showing "failed to fetch laibraries"

**Comment by sahara101** [comment]
Please add logs.

**Comment by xiongster** [comment]
INFO:utils.plex_service:Parameters - URL: True, Token: True, Libraries: []
INFO:utils.plex_service:Using ENV for PLEX_MOVIE_LIBRARIES
INFO:utils.plex_service:Connecting to Plex server at 192.168.1.188
ERROR:utils.plex_service:Failed to connect to Plex server: Invalid URL '192.168.1.188/': No scheme supplied. Perhaps you meant https://192.168.1.188/?
ERROR:movie_selector:Failed to initialize Plex service: Invalid URL '192.168.1.188/': No scheme supplied. Perhaps you meant https://192.168.1.188/?
INFO:movie_selector:Jellyfin service is not configured
INFO:movie_selector:Overseerr service is disabled or not configured
INFO:utils.overseerr_service:Overseerr service not initialized - missing configuration or disabled
INFO:movie_selector:Services initialization complete:
INFO:movie_selector:- Plex: False
INFO:movie_selector:- Jellyfin: False
INFO:movie_selector:- Overseerr: False
INFO:movie_selector:- Trakt: False
INFO:utils.settings.routes:Services reinitialization successful
INFO:utils.settings.routes:Settings saved to disk
INFO:utils.settings.routes:Checking field plex.url for ENV control
INFO:utils.settings.routes:Settings updated successfully for category plex
INFO:utils.settings.routes:Media service settings changed, will reinitialize services
INFO:movie_selector:Settings loaded - Homepage Mode: False
INFO:movie_selector:Service availability - Plex: True, Jellyfin: False
INFO:movie_selector:Initializing TMDB service...
INFO:utils.tmdb_service:TMDB service initialized
INFO:movie_selector:TMDB service initialized successfully
INFO:movie_selector:Starting services initialization
INFO:movie_selector:Current settings state:
INFO:movie_selector:Initializing Plex service...
INFO:utils.plex_service:Initializing PlexService
INFO:utils.plex_service:Parameters - URL: True, Token: True, Libraries: []
INFO:utils.plex_service:Using ENV for PLEX_MOVIE_LIBRARIES
INFO:utils.plex_service:Connecting to Plex server at 192.168.1.188:32400
ERROR:utils.plex_service:Failed to connect to Plex server: No connection adapters were found for '192.168.1.188:32400/'
ERROR:movie_selector:Failed to initialize Plex service: No connection adapters were found for '192.168.1.188:32400/'
INFO:movie_selector:Jellyfin service is not configured
INFO:movie_selector:Overseerr service is disabled or not configured
INFO:utils.overseerr_service:Overseerr service not initialized - missing configuration or disabled
INFO:movie_selector:Services initialization complete:
INFO:movie_selector:- Plex: False
INFO:movie_selector:- Jellyfin: False
INFO:movie_selector:- Overseerr: False
INFO:movie_selector:- Trakt: False
INFO:utils.settings.routes:Services reinitialization successful
INFO:utils.settings.routes:Settings saved to disk
INFO:utils.settings.routes:Checking field plex.movie_libraries for ENV control
INFO:utils.settings.routes:Settings updated successfully for category plex
INFO:utils.settings.routes:Media service settings changed, will reinitialize services
INFO:movie_selector:Settings loaded - Homepage Mode: False
INFO:movie_selector:Service availability - Plex: True, Jellyfin: False
INFO:movie_selector:Initializing TMDB service...
INFO:utils.tmdb_service:TMDB service initialized
INFO:movie_selector:TMDB service initialized successfully
INFO:movie_selector:Starting services initialization
INFO:movie_selector:Current settings state:
INFO:movie_selector:Initializing Plex service...
INFO:utils.plex_service:Initializing PlexService
INFO:utils.plex_service:Parameters - URL: True, Token: True, Libraries: Movies
INFO:utils.plex_service:Connecting to Plex server at 192.168.1.188:32400
ERROR:utils.plex_service:Failed to connect to Plex server: No connection adapters were found for '192.168.1.188:32400/'
ERROR:movie_selector:Failed to initialize Plex service: No connection adapters were found for '192.168.1.188:32400/'
INFO:movie_selector:Jellyfin service is not configured
INFO:movie_selector:Overseerr service is disabled or not configured
INFO:utils.overseerr_service:Overseerr service not initialized - missing configuration or disabled
INFO:movie_selector:Services initialization complete:
INFO:movie_selector:- Plex: False
INFO:movie_selector:- Jellyfin: False
INFO:movie_selector:- Overseerr: False
INFO:movie_selector:- Trakt: False
INFO:utils.settings.routes:Services reinitialization successful
INFO:utils.settings.routes:Settings saved to disk
INFO:utils.lgtv_discovery:arp-scan output:
INFO:utils.lgtv_discovery:Interface: eth0, type: EN10MB, MAC: 02:42:ac:11:00:0a, IPv4: 172.17.0.10
Starting arp-scan 1.10.0 with 65536 hosts (https://github.com/royhills/arp-scan)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered)
172.17.0.2      02:42:ac:11:00:02       (Unknown: locally administered)
172.17.0.3      02:42:ac:11:00:03       (Unknown: locally administered)
172.17.0.4      02:42:ac:11:00:04       (Unknown: locally administered)
172.17.0.5      02:42:ac:11:00:05       (Unknown: locally administered)
172.17.0.6      02:42:ac:11:00:06       (Unknown: locally administered)
172.17.0.7      02:42:ac:11:00:07       (Unknown: locally administered)
172.17.0.8      02:42:ac:11:00:08       (Unknown: locally administered)
172.17.0.9      02:42:ac:11:00:09       (Unknown: locally administered)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered) (DUP: 2)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered) (DUP: 3)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered) (DUP: 4)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered) (DUP: 5)
172.17.0.1      02:42:b5:8f:7f:2d       (Unknown: locally administered) (DUP: 6)

14 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 65536 hosts scanned in 263.605 seconds (248.61 hosts/sec). 9 responded

INFO:movie_selector:Scan complete. Found 0 LG devices

**Comment by sahara101** [comment]
If you use the plex Ip you need to specify the plex port as well. 

http://192.168.1.188:32400

**Comment by sahara101** [comment]
Yes. Please use fqdn for https or ip for http
