### ISSUE TITLE
dont get the other features when enabled. 

### ISSUE THREAD

**Issue by shedman214** [sahara101/Movie-Roulette#18]
I have enabled all the feuatures but they don't show on my side. Is there there something I'm missing 
![image](https://github.com/user-attachments/assets/bfe82752-9f57-4047-b17d-74cc29bf5bec)
![image](https://github.com/user-attachments/assets/8aa373ab-1734-4308-b2e9-cc337d088251)

**Comment by sahara101** [comment]
You enabled homepage mode as well. Please disable it for the butona to appear. 

I will add some descriptions.

**Comment by sahara101** [comment]
v3.1.1 released which includes a description for HOMEPAGE_MODE
