### ISSUE TITLE
Doesn't load on large libraries.

### ISSUE THREAD

**Issue by jbeck22** [sahara101/Movie-Roulette#3]
Doesn't seem to like large libraries.  I have a test library of 1 movie and it works fine.  When I moved on to my main library it doesn't load at all...

movie-roulette2  | ERROR:utils.cache_manager:Error updating cache: 'Stream'
movie-roulette2  | INFO:movie_selector:Cache file does not exist.
movie-roulette2  | INFO:movie_selector:Loaded 0 movies from cache.
movie-roulette2  | INFO:movie_selector:Loaded 0 movies from cache.
movie-roulette2  | INFO:movie_selector:Loaded 0 movies from cache.
movie-roulette2  | INFO:movie_selector:Loaded 0 movies from cache.

**Comment by sahara101** [comment]
It can take some time to build the cache on large libraries. You should see a progress bar, does it not start loading?

**Comment by jbeck22** [comment]
I see the progress bar, but it does not move or fill and just disappears altogether.

**Comment by jbeck22** [comment]
![image](https://github.com/user-attachments/assets/5d0ab03e-8ce3-4062-8fac-5edd7b9e3a29)

**Comment by jbeck22** [comment]
I also confirmed that the json file isn't being created in the configured /config folder.  The current_movie.json file is created if something in my library is playing.  Also -- :4000/poster works as planned.

**Comment by sahara101** [comment]
How big is the library?

**Comment by sahara101** [comment]
Paste the contents of /debug_plex please

**Comment by jbeck22** [comment]
{
  "cache_file_exists": false,
  "cached_movies": 0,
  "loaded_from_cache": false,
  "movies_library_name": null,
  "plex_url": "http://192.168.1.238:32400",
  "total_unwatched_movies": 718
}

**Comment by jbeck22** [comment]
> Paste the contents of /debug_plex please

2,481 movies

**Comment by sahara101** [comment]
Maybe a bug from this "movies_library_name": null,

I’ll check it out.

**Comment by jbeck22** [comment]
here is the compose file in case it helps:

services:
  movie-roulette:
    image: ghcr.io/sahara101/movie-roulette:latest
    container_name: movie-roulette
    pull_policy: always
    environment:
      #Homepage ENV
      HOMEPAGE_MODE: "FALSE"
      #Plex ENV
      PLEX_URL: http://192.168.1.238:32400
      PLEX_TOKEN: xxxxxxxxx
      PLEX_MOVIE_LIBRARIES: Movies
        #Default movies, add more with comma delimiter A,B,C
        #Poster ENV
      TZ: America/New_York
      DEFAULT_POSTER_TEXT: My Cool Cinema
      PLEX_POSTER_USERS: xxxxxxx #Plex username, add more with comma delimiter A,B,C
      PUID: 1000
      PGID: 1000
      #      JELLYFIN_POSTER_USERS: "" #Jellyfin username, add more with comma delimiter A,B,C
      #Jellyfin ENV
      #      JELLYFIN_URL: " "
      #      JELLYFIN_API_KEY: " "
      #      JELLYFIN_USER_ID: " "
      #Client ENV
      APPLE_TV_ID: xxxxxxxxxxx
    #      LGTV_IP: " "
    #      LGTV_MAC: " "
    network_mode: host
    volumes:
      - /mnt/user/appdata/movie-roulette/data:/app/data
    restart: unless-stopped
networks: {}

**Comment by sahara101** [comment]
Can you try the :dev image? You should now also see debug logs for the cache.

**Comment by jbeck22** [comment]
pulled the dev image, deleted my docker image and container -- started from scratch.

{
  "cache_file_exists": false,
  "cached_movies": 0,
  "loaded_from_cache": false,
  "movies_library_name": "Movies",
  "plex_url": "http://192.168.1.238:32400",
  "total_unwatched_movies": 723
}


Can I pull the logs from somewhere....don't want to just copy and paste here if possible.

**Comment by sahara101** [comment]
Do you see the cache loading in the docker log? You can paste it on pastebin for example. 

Inspect on the web page could also show some info.

**Comment by jbeck22** [comment]
Here are the logs:
[https://pastebin.com/J3vjrM7Y](url)

**Comment by jbeck22** [comment]
Here is the webpage inspection:

[https://pastebin.com/UMcNLqBy](url)

**Comment by sahara101** [comment]
Thank you, seems some movie does not have the stream key which makes the cache exit. Please test the new :dev image. You should also get a log if a movie is missing keys.

I do not have such a large library so I cannot test myself...

**Comment by sahara101** [comment]
PLease test :dev again, also in an incognito tab.

**Comment by jbeck22** [comment]
seems to be better now.  Now I get a bunch of unwatched movies that I can cycle through.

New problem is that the filter button isn't loading any of the genres or years.  PG Rating seems to be working ok.

**Comment by sahara101** [comment]
Yes, seems some new issues because of the latest change. I will work on it tonight.

**Comment by sahara101** [comment]
genres and years work fine for me though, can you paste the new logs please?

**Comment by jbeck22** [comment]
I restarted the container and now it all seems to be working.  good job crushing those bugs!  I have an idea for an enhancement -- do you want it as a separate item or included inline here?

**Comment by sahara101** [comment]
Glad to hear! Separate item please. Tell me, don’t you have the progress loading bar appearing more times than the first one? I will fix that (came with latest change) but it is weird if you don’t see it 😁

**Comment by jbeck22** [comment]
the progress bar was all over the place -- would jump to 50% and then back down to around 10-15% and then back up to 50%.  Up, down, up, down -- like that.  until it was done.

**Comment by sahara101** [comment]
The sporadic loading (cause of the cache refresh is solved in the next image)
