### ISSUE TITLE
[enhancement] use radio buttons for filters

### ISSUE THREAD

**Issue by jbeck22** [sahara101/Movie-Roulette#5]
in the filters section maybe consider using radio buttons instead. this would allow you to choose more than 1 item for the filter.

For example:  Maybe I want to watch a comedy, but not an animated comedy or I wanted to watch a movie that i haven't seen from the "90's" -- I would just choose all of the years that are available that are in the "90's" and then refresh until I find what I want.

**Comment by sahara101** [comment]
Released in v2.1, please update to :latest image.
