### ISSUE TITLE
lock settings/disable settings page using env variable

### ISSUE THREAD

**Issue by Pesoen** [sahara101/Movie-Roulette#9]
i self host my jellyfin server so my family can use it. this includes having it available on the internet using my domain. i want to have this available as well, but without any configuration options available, as i have them all set using env variables.

what i would like is a way to block the settings page, and hide the link when setting and env variable. when trying to access /settings you would get a 404 or similar, and setting the env variable to false will enable it again.

this way, i can have it available, similar to jellyfin, but also locked down so bots cannot gain access to the settings page. the reason jellyfin is available is because it has a login system blocking access unless you have a login or a valid api key.

on a side note, love this. if i am indecisive i just fire this up and see what it suggests :) love the simplicity :D

**Comment by sahara101** [comment]
Hi, thanks!
The settings are all locked when set via ENV. Does this not help? If not, I can do something, sure

**Comment by Pesoen** [comment]
true the settings are locked down, but i want to completely hide that there are settings to begin with.

currently i am hiding movie roulette behind a nginx auth, since i know bots and scrappers know of my domain, and as soon as they see settings they will look in there. and while the api key itself is hidden, i would still prefer just locking the settings away, as i am the only one who should need access to it. the main page i am fine with leaving open to the public, as all it does is display information about a random movie, but the settings does not need to be available to anyone other than me, and i can restart the container with that env setting changed if i need to modify anything.

i have configured it all, and moved the settings into ENV to lock it, but it still does not need to show for most of the people who might want to access it.

**Comment by sahara101** [comment]
Understood, will do :)

**Comment by sahara101** [comment]
@Pesoen 
It is released in the new version. 

Please use the ENV  DISABLE_SETTINGS: TRUE
